# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderer',
            field=models.CharField(default=b'None', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
