# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20170224_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inStock',
            field=models.BooleanField(default=False),
        ),
    ]
