# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_item_instock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='inStock',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderItems',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=b''),
        ),
    ]
