# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-27 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20170227_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='orderer',
        ),
    ]
